### ISSUE TITLE
This block of commented-out lines of code should be removed.

### ISSUE THREAD

**Issue by rochuk** [Vibhor7398/OSMDashboard-Winter-2024-SOEN-6431-Group14#8]
<img width="1470" alt="Screenshot 2024-02-13 at 8 57 20 PM" src="https://github.com/Vibhor7398/OSMDashboard-Winter-2024-SOEN-6431-Group14/assets/117546629/8b12c4fb-f71e-4f3c-8a8e-c5645c224360">

**Description**
The analysis of MapsActivity.java has identified a section of code that is commented out but not actively utilized in the application. This redundant code block represents technical debt and should be addressed. 

**Location**
 src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java

**Proposed Solution**

1. Proceed to locate the line of code that is causing the technical debt.
2. The solution is to delete the block of commented- out lines of code entirely.
3. After the removal of block of code, it is essential to conduct comprehensive testing to verify continued functionality of the code.
4. Upon confirmation of the code's stability, commit the changes and proceed to create a pull request.

**Reason**
Commented out code adds noise to the file making it harder for the developers to comprehend the active logic flow. It distracts the focus of the developers from the actual functionality of the code. It also has an impact on the file size. Removing it ensures that developers can quickly grasp the purpose and functionality of code. By eliminating the block of code, the technical debt associated with MapsActivity.java is reduced making the code base **maintainable** and sustainable in long term.

**Comment by Vibhor7398** [comment]
The issue has been fixed.
